create table
  public.bens (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null default now(),
    patrimonio text not null,
    imagem text not null,
    numero_serie text null,
    estado_bem text not null,
    bem_particular boolean not null,
    indica_desfazimento boolean not null,
    localidade_id bigint not null,
    inventario_id bigint not null,
    usuario_id bigint not null,
    descricao text not null,
    observacoes text null,
    sem_etiqueta boolean null default false,
    ano_inventario text not null default ''::text,
    constraint bens_pkey primary key (id),
    constraint bens_inventario_id_fkey foreign key (inventario_id) references inventario_localidade (id),
    constraint bens_localidade_id_fkey foreign key (localidade_id) references localidades (id),
    constraint bens_usuario_id_fkey foreign key (usuario_id) references usuarios (id)
  ) tablespace pg_default;

create trigger trigger_atualiza_status_inventario
after insert on bens for each row
execute function atualiza_status_inventario ();