create table
  public.inventario_localidade (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    localidade_id bigint not null,
    relatorio text null,
    usuario_id bigint null,
    ano text not null,
    status public.statusLocalidade null default 'nao_iniciada'::"statusLocalidade",
    relatorio_path text null,
    finalizada_em timestamp with time zone null default now(),
    observacao text null,
    constraint inventario_localidade_pkey primary key (id),
    constraint inventario_localidade_localidade_id_fkey foreign key (localidade_id) references localidades (id),
    constraint inventario_localidade_usuario_id_fkey foreign key (usuario_id) references usuarios (id)
  ) tablespace pg_default;