create table
  public.localidades (
    id bigint generated by default as identity not null,
    nome character varying(255) not null,
    constraint localidade_pkey primary key (id),
    constraint localidades_id_key unique (id)
  ) tablespace pg_default;