create table
  public.usuarios (
    id bigint generated by default as identity not null,
    nome character varying(255) not null,
    cpf text not null,
    siape character varying(20) not null,
    email character varying(255) not null,
    uid uuid null,
    admin boolean null,
    constraint usuario_pkey primary key (id),
    constraint usuarios_id_key unique (id)
  ) tablespace pg_default;